version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: gunicorn apaxhr.apaxhr.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.dev
    volumes:
      - .:/code
