# Generated by Django 3.0 on 2020-01-10 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id_code',
            field=models.CharField(max_length=20, null=True, verbose_name='employee id number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('ap', 'Applicant'), ('trial', 'Initial Training'), ('em', 'Employed'), ('ps', 'Pause')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=25, null=True, validators=[django.core.validators.RegexValidator('^[a-z A-Z]*$', 'Only Alphabetic characters allowed')], verbose_name='Surname, Given Names as on passport'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=10),
        ),
    ]
