# Generated by Django 2.2.9 on 2020-01-02 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=25)),
                ('middle_name', models.CharField(default='', max_length=25)),
                ('last_name', models.CharField(default='', max_length=25)),
                ('bio', models.TextField(default='', max_length=1000)),
                ('employee_role', models.CharField(choices=[('ftt', 'Full Time Teacher'), ('pt', 'Part Time Teacher'), ('training', 'Teacher in Training'), ('ht', 'Head Teacher'), ('st', 'Senior Teacher'), ('sup', 'Support Staff')], default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateTimeField()),
                ('pdf', models.FileField(null=True, upload_to='work_permits')),
                ('image', models.ImageField(blank=True, null=True, upload_to='work_permits')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='RegistryOfStayForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateTimeField()),
                ('issued', models.DateTimeField()),
                ('pdf', models.FileField(null=True, upload_to='document_images')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='PublicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=25)),
                ('image', models.ImageField(null=True, upload_to='social')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField()),
                ('issue_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='passports')),
                ('pdf', models.FileField(upload_to='passports')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_hr.Employee')),
            ],
        ),
    ]
