# Generated by Django 3.0 on 2020-01-18 09:07

import apaxhr.storage_backends
import core_hr.models
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=apaxhr.storage_backends.PrivateMediaStorage(), upload_to='kpi_certificates')),
                ('message_text', models.TextField(max_length=1000, verbose_name='Enter award message for email here')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DegreeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(blank=True)),
                ('expiration_date', models.DateField()),
                ('dob', models.DateField()),
                ('place_of_issue', django_countries.fields.CountryField(default='AQ', max_length=2)),
                ('image', models.ImageField(storage=apaxhr.storage_backends.PrivateMediaStorage(), upload_to='passports')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistryOfStay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_address', models.CharField(max_length=100)),
                ('landlords_name', models.CharField(max_length=100)),
                ('landlords_cell_phone', models.CharField(max_length=25)),
                ('landlords_email', models.EmailField(max_length=25)),
                ('expiration_date', models.DateField(default=core_hr.models.default_ros_expiration)),
                ('issued', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(storage=apaxhr.storage_backends.PrivateMediaStorage(), upload_to='ros_images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rs', 'Resume'), ('cv', 'Curriculum Vitae')], max_length=20)),
                ('image', models.ImageField(storage=apaxhr.storage_backends.PrivateMediaStorage(), upload_to='resumes')),
                ('added', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeachingCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('c', 'CELTA'), ('ts', 'TESOL'), ('tf', 'TEFL'), ('ot', 'other')], max_length=15)),
                ('image', models.ImageField(storage=apaxhr.storage_backends.PrivateMediaStorage(), upload_to='tefl_certs')),
                ('added', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(default=core_hr.models.default_work_permit_expiration)),
                ('image', models.ImageField(storage=apaxhr.storage_backends.PrivateMediaStorage(), upload_to='work_permit_images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
