# Generated by Django 3.0 on 2019-12-28 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 6, 56, 2, 372063)),
        ),
        migrations.AlterField(
            model_name='passport',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 6, 56, 2, 372063)),
        ),
        migrations.AlterField(
            model_name='registryofstayform',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 6, 56, 2, 372063)),
        ),
        migrations.AlterField(
            model_name='registryofstayform',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 6, 56, 2, 372063)),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 6, 56, 2, 372063)),
        ),
    ]
