# Generated by Django 3.0 on 2020-01-16 08:03

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0003_achievementcertificate_degreedocument_resume_teachingcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='place_of_issue',
            field=django_countries.fields.CountryField(default='AQ', max_length=2),
        ),
    ]
