# Generated by Django 3.0 on 2020-01-16 08:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_hr', '0004_auto_20200116_0803'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistryOfStayForm',
            new_name='RegistryOfStay',
        ),
    ]
