version: "3"
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - "5672"
      - "15672"

  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ../nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    container_name: prod_app
    build: ../app
    stdin_open: true
    tty: true
    volumes:
      - ./app:/code
      # - ./app/media:/media
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    command: python3 start_server.py prod
