version: "3.7"
services:
  web:
    container_name: demo_app
    build: ../app
    stdin_open: true
    tty: true
    volumes:
      - ./app:/code
    env_file:
      - .env.dev
    ports:
      - "80:8000"
    command: python3 .start_scripts/start_demo_server.py