#!/bin/bash
unset SQL_USER
unset SQL_PASSWORD
unset SQL_HOST
unset SQL_ENGINE
unset SQL_PORT
unset SQL_NAME
unset SECRET_KEY
unset DJANGO_ALLOWED_HOSTS
unset SQL_DATABASE
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_STORAGE_BUCKET_NAME
