# Generated by Django 3.0 on 2020-03-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employment', '0001_initial'),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerteacher',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employment.SalariedPosition'),
        ),
        migrations.AddField(
            model_name='centerroom',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.LearningCenter'),
        ),
        migrations.AddField(
            model_name='centerdailyschedule',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centers.LearningCenter'),
        ),
        migrations.AddField(
            model_name='centerdailyschedule',
            name='weekly_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.CenterWeeklySchedule'),
        ),
        migrations.AddField(
            model_name='biweeklyclass',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.LearningCenter'),
        ),
        migrations.AddField(
            model_name='biweeklyclass',
            name='day1_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day1_teacher', to='centers.CenterTeacher'),
        ),
        migrations.AddField(
            model_name='biweeklyclass',
            name='day2_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day2_teacher', to='centers.CenterTeacher'),
        ),
        migrations.AddField(
            model_name='biweeklyclass',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.CenterRoom'),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='containing_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.CenterDailySchedule'),
        ),
        migrations.AddConstraint(
            model_name='centerteacher',
            constraint=models.UniqueConstraint(fields=('center', 'teacher'), name='teacher_constraint'),
        ),
        migrations.AddConstraint(
            model_name='centerroom',
            constraint=models.UniqueConstraint(fields=('center', 'name'), name='room_constraint'),
        ),
        migrations.AddConstraint(
            model_name='biweeklyclass',
            constraint=models.UniqueConstraint(fields=('center', 'room', 'block', 'day1'), name='double_book_day1'),
        ),
        migrations.AddConstraint(
            model_name='biweeklyclass',
            constraint=models.UniqueConstraint(fields=('center', 'room', 'block', 'day2'), name='double_book_day2'),
        ),
    ]
